options:
  platform: psx
  basename: stno0
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/NO0/NO0.BIN
  asm_path: asm/us/st/no0
  asset_path: assets/st/no0
  src_path: src/st/no0
  ld_script_path: build/us/stno0.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stno0.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stno0.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.stno0.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  include_macro_inc: false
sha1: d07f054f9dc8ef639257aca01deb1f24a2811924
segments:
  - name: stno0
    type: code
    start: 0
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, data]
      - [0x41368, .rodata, first_c_file]
      - [0x4137C, .rodata, e_red_door]
      - [0x41394, .rodata, e_collect]
      - [0x4139C, .rodata, e_collect]
      - [0x413A4, .rodata, e_collect]
      - [0x413AC, .rodata, e_collect]
      - [0x413B4, .rodata, e_collect]
      - [0x413BC, .rodata, e_collect]
      - [0x413C4, .rodata, e_collect]
      - [0x413CC, .rodata, e_collect]
      - [0x413D4, .rodata, e_collect]
      - [0x413DC, .rodata, e_collect]
      - [0x413E4, .rodata, e_collect]
      - [0x41404, .rodata, e_collect]
      - [0x4141C, .rodata, blit_char]
      - [0x4142C, .rodata, e_misc]
      - [0x41454, .rodata, e_misc]
      - [0x41468, .rodata, e_misc]
      - [0x41490, .rodata, e_misc]
      - [0x414A8, .rodata, e_stage_name]
      - [0x414D8, .rodata, e_stage_name]
      - [0x414EC, .rodata, 4F4A8]
      - [0x41504, .rodata, 4F4A8]
      - [0x41550, .rodata, 4F4A8]
      - [0x41588, .rodata, 4F4A8]
      - [0x415C8, .rodata, 4F4A8]
      - [0x41610, .rodata, 4F4A8]
      - [0x41624, .rodata, 4F4A8]
      - [0x4166C, .rodata, 4F4A8]
      - [0x41684, .rodata, 4F4A8]
      - [0x4168C, .rodata, 4F4A8]
      - [0x416A0, .rodata, 4F4A8]
      - [0x416F0, .rodata, 4F4A8]
      - [0x4171C, .rodata, 4F4A8]
      - [0x41738, .rodata, 4F4A8]
      - [0x41770, .rodata, 4F4A8]
      - [0x4178C, .rodata, 4F4A8]
      - [0x417C0, .rodata, 4F4A8]
      - [0x41804, .rodata, 4F4A8]
      - [0x41818, .rodata, 4F4A8]
      - [0x41834, .rodata, 4F4A8]
      - [0x4184C, .rodata, prim_helpers]
      - [0x41854, c, first_c_file]
      - [0x43788, c, st_update]
      - [0x43BBC, c, collision]
      - [0x45378, c, create_entity]
      - [0x45EF0, c, e_red_door]
      - [0x46BA0, c, e_room_fg]
      - [0x46C8C, c, popup]
      - [0x46FBC, c, e_particles]
      - [0x47800, c, st_common]
      - [0x48CB0, c, e_collect]
      - [0x4A21C, c, blit_char]
      - [0x4A4CC, c, e_misc]
      - [0x4E654, c, e_stage_name]
      - [0x4F4A8, c, 4F4A8]
      - [0x5E09C, c, prim_helpers]
      - [0x5E8CC, sbss]
  - [0x5F58C]