options:
  platform: psp
  basename: ric
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/ric.bin
  asm_path: asm/pspeu/ric_psp
  asset_path: assets/ric
  src_path: src/ric_psp
  ld_script_path: build/pspeu/ric.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.ric.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.ric.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.ric.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: false
  asm_jtbl_label_macro: jlabel
  symbol_name_format: psp_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
    .include "macro.inc"
segments:
  - [0x0, bin, mwo_header]
  - name: ric
    type: code
    start: 0x80
    vram:  0x092A6280
    bss_size: 0x1F80
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c]
      - [0x32A0, c]
      - [0x3CA0, c]
      - [0x4B60, c]
      - [0x6DB0, c]
      - [0x7CA0, c]
      - [0x7F50, c]
      - [0x9400, c]
      - [0x9480, c]
      - [0x97D0, c]
      - [0x9890, c]
      - [0x9EF0, c]
      - [0xACA0, c]
      - [0xAED0, c]
      - [0xB070, c]
      - [0xBAD0, c]
      - [0xD2F0, c]
      - [0xF590, c]
      - [0x14340, c]
      - [0x15660, c]
      - [0x18370, c]
      - [0x1BCF0, c]
      - [0x1C3A0, c]
      - [0x1C990, c]
      - [0x1EA00, c]
      - [0x23280, c]
      - [0x27F70, c]
      - [0x28400, data]
      - {type: bss, vram: 0x92D6680}
  - [0x30400]
