options:
  platform:     psp
  basename:     w0_041
  base_path:    ..
  build_path:   build/pspeu
  target_path:  disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/w0_041.bin
  asm_path:     asm/pspeu/weapon/w0_041
  asset_path:   assets/weapon/w0_041
  src_path:     src/weapon/w0_041
  ld_script_path: build/pspeu/w0_041.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.w0_041.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.w0_041.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.pspeu.w0_041.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_bss_is_noload: True
  disasm_unknown: True
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
    .include "macro.inc"
sha1: 26111b15760c15b759b8c0ffaf37e6027ff2611b

segments:
  - [0x0, bin, header]
  - name: w0_041
    type: code
    start: 0x00000080
    vram:  0x092E7680
    bss_size: 0x500
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, w_041]
      - {type: bss, vram: 0x092ed480}
  - [0x1050]
